"""Baseline and Add entity models

Revision ID: a1ad12127da9
Revises: 
Create Date: 2026-09-17 17:44:13.520794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1ad12127da9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('canonical_value', sa.String(), nullable=False),
    sa.Column('display_value', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'canonical_value', name='uq_entity_node_identity')
    )
    op.create_index('idx_entity_tenant_type', 'entity_nodes', ['tenant_id', 'entity_type'], unique=False)
    op.create_index(op.f('ix_entity_nodes_current_risk_score'), 'entity_nodes', ['current_risk_score'], unique=False)
    op.create_index(op.f('ix_entity_nodes_entity_type'), 'entity_nodes', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_nodes_last_seen'), 'entity_nodes', ['last_seen'], unique=False)
    op.create_index(op.f('ix_entity_nodes_tenant_id'), 'entity_nodes', ['tenant_id'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('last_event_id', sa.String(), nullable=True),
    sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_entity_id', 'target_entity_id', 'relation_type', name='uq_entity_rel_identity')
    )
    op.create_index(op.f('ix_entity_relationships_last_seen'), 'entity_relationships', ['last_seen'], unique=False)
    op.create_index(op.f('ix_entity_relationships_relation_type'), 'entity_relationships', ['relation_type'], unique=False)
    op.create_index(op.f('ix_entity_relationships_source_entity_id'), 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_target_entity_id'), 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_tenant_id'), 'entity_relationships', ['tenant_id'], unique=False)
    op.alter_column('cases', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('cases', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('detection_rules', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('detection_rules', 'rule_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'yaml'::character varying"))
    op.alter_column('detection_rules', 'version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'1.0.0'::character varying"))
    op.alter_column('detection_rules', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'AetherGuard'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detection_rules', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'AetherGuard'::character varying"))
    op.alter_column('detection_rules', 'version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'1.0.0'::character varying"))
    op.alter_column('detection_rules', 'rule_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'yaml'::character varying"))
    op.alter_column('detection_rules', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('cases', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('cases', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.drop_index(op.f('ix_entity_relationships_tenant_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_target_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_relation_type'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_last_seen'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_entity_nodes_tenant_id'), table_name='entity_nodes')
    op.drop_index(op.f('ix_entity_nodes_last_seen'), table_name='entity_nodes')
    op.drop_index(op.f('ix_entity_nodes_entity_type'), table_name='entity_nodes')
    op.drop_index(op.f('ix_entity_nodes_current_risk_score'), table_name='entity_nodes')
    op.drop_index('idx_entity_tenant_type', table_name='entity_nodes')
    op.drop_table('entity_nodes')
    # ### end Alembic commands ###
