"""Production schema

Revision ID: 77d667da55a8
Revises: 
Create Date: 2026-09-03 18:27:16.800902

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d667da55a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('source_signal_ids', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_table('iocs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('ioc_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('threat_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iocs_ioc_type'), 'iocs', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_iocs_tenant_id'), 'iocs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_iocs_value'), 'iocs', ['value'], unique=False)
    op.create_table('security_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('ack_notes', sa.String(length=1000), nullable=True),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('ai_verdict', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence', sa.String(length=20), nullable=True),
    sa.Column('ai_analysis', sa.String(length=5000), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=True),
    sa.Column('mitre_tactics', sa.JSON(), nullable=True),
    sa.Column('source_alert_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_signals_tenant_id'), 'security_signals', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_signals_tenant_id'), table_name='security_signals')
    op.drop_table('security_signals')
    op.drop_index(op.f('ix_iocs_value'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_tenant_id'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_ioc_type'), table_name='iocs')
    op.drop_table('iocs')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
